### ISSUE TITLE
broad suggestion/issue

### ISSUE THREAD

**Issue by c17ju** [dbh937/Planbook#27]
I didn't find any actual bugs except for that the format is super weird on phones. An issue that I do see is that teachers hate when people are typing things (other than notes) in class so they should be briefed on the new planner. Side note, is there a way so that it can notify us when we have a major assessment or test or project due? Also there should be a way to view months at a time as opposed to just scrolling through week by week by week.

**Comment by dbh937** [comment]
Fixed the format for phones!

**Comment by dbh937** [comment]
Month view in the works
